version: "3.8"

services:
  db:
    image: mysql
    hostname: mysql
    volumes:
      - ./db/init-db.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 3306:3306
    expose:
      - 3306
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: test
  form76-generator:
    image: form76-generator:1.0.0
    ports:
      - "80:80"
    build:
      context: ./
      dockerfile: ./Dockerfile

