version: "3.8"

services:
  mysql-db:
    image: mysql:8.2
    hostname: mysql
    volumes:
      - db-data:/var/lib/mysql
      # - ./db/init-db.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 3306:3306
    expose:
      - 3306
    restart: always
    environment:
      MYSQL_DATABASE: form76-generator-db
      MYSQL_ROOT_PASSWORD: test
    networks:
      - localnet
  server:
    depends_on:
      - mysql-db
    container_name: server
    restart: always
    build:
      context: ./server
      dockerfile: Dockerfile
    environment:
      - DB_HOST=mysql:3306
      - DB_USER=root
      - DB_PASSWORD=test
      - DB_DATABASE=form76-generator-db
    ports:
      - "8080:8080"
    networks:
      - localnet
  frontend:
    depends_on:
      - server
    container_name: frontend
    restart: always
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - VITE_BACKEND_HOST
    ports:
      - "80:80"
    networks:
      - localnet
volumes:
  db-data: {}

networks:
  localnet:
    driver: bridge

